### ISSUE TITLE
[ForgotPassword] empty placeholders

### ISSUE THREAD

**Issue by krava77** [modxcms/Login#166] opened 2020-04-05 09:27 UTC
Hello!
Could you put array to placeholders before returning the chunk?
row 82
file `core/components/login/controllers/web/ForgotPassword.php`
Code `$this->modx->setPlaceholders($this->placeholders);` 

Thank you!

**Comment by Jako** [comment] 2020-07-26 17:06
Duplicate of #162

**Closed by Jako** 2020-07-26 17:06 UTC
