### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by I6BNzuEL4O62m5N76veO** [modxcms/Login#124] opened 2018-03-01 07:38 UTC
[2018-02-28 20:00:10] (ERROR @ /.../components/login/controllers/web/ForgotPassword.php : 78) PHP warning: htmlspecialchars() expects parameter 1 to be string, array given

**Comment by Jako** [comment] 2018-03-01 07:50
Duplicate of #114

**Closed by Jako** 2018-03-01 07:50 UTC
