### ISSUE TITLE
Submitted variables are overwritten by DB values in UpdateProfile

### ISSUE THREAD

**Issue by ambienthack** [modxcms/Login#34] opened 2015-01-04 10:26 UTC
I suppose there is some mistake in logic of `process()` of UpdateProfile controller.
If validation fails, submitted variables (I mean those inside `$_POST`) are not exposed using placeholders, instead DB variables are reloaded.

**Comment by Jako** [comment] 2016-12-01 21:41
Duplicate of #29

**Closed by Jako** 2016-12-01 21:41 UTC
